/**
 * System Configurations Constants
 */
export const CONFIG_CONSTANTS = {
  HTTP_TIMEOUT_MS: 30000,
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 1000,
  WEBSOCKET_RECONNECT_INTERVAL_MS: 3000,
  WEBSOCKET_MAX_RECONNECT_ATTEMPTS: 5,
  DEBOUNCE_DELAY_MS: 300,
  TOAST_DURATION_MS: 4000,
} as const;
